db:
   userName: "MulesoftTest"
   
   
api:
    id: "20439524"

queries:
   customer:
      missingSFID: "select c.cust_num, c.cust_seq, ca.name, ca.city, ca.country,ca.site_ref from dev_app.dbo.customer_mst c left outer join dev_app.dbo.custaddr_mst ca on c.cust_num =ca.cust_num and c.cust_seq =ca.cust_seq and c.site_ref = ca.site_ref where c.cust_seq = 0" 
      customerByID: "select c.cust_num from dev_app.dbo.customer_mst c where c.cust_seq = 0 and c.cust_num = :Id"
   enduser:
      missingSFID: "select enduser_code, legalentityname from dev_app.dbo.uec_enduser"
   serviceOrder:
      openServiceOrders: "SELECT sro.sro_num, sro.sro_stat FROM dev_app.dbo.fs_sro_mst sro WHERE sro.sro_stat = 'O' ORDER BY sro.sro_num OFFSET 0 ROWS FETCH NEXT 5 ROWS ONLY"