db:
   userName: "MulesoftTest"
   
   
api:
    id: "20439524"

queries:
   customer:
      missingSFID: "select c.cust_num, c.cust_seq, ca.name, ca.city, ca.country,ca.site_ref from dev_app.dbo.customer_mst c left outer join dev_app.dbo.custaddr_mst ca on c.cust_num =ca.cust_num and c.cust_seq =ca.cust_seq and c.site_ref = ca.site_ref where c.cust_seq = 0" 
      customerByID: "select c.cust_num from dev_app.dbo.customer_mst c where c.cust_seq = 0 and c.cust_num = :Id"
   enduser:
      missingSFID: "select enduser_code, legalentityname from dev_app.dbo.uec_enduser"
      customerByID: "SELECT enduser_code, legalentityname FROM dev_app.dbo.uec_enduser WHERE enduser_code = :Id"
   serviceOrder:
      openServiceOrders: "SELECT sro.sro_num, sro.sro_stat FROM dev_app.dbo.fs_sro_mst sro WHERE sro.sro_stat = 'O' ORDER BY sro.sro_num OFFSET 0 ROWS FETCH NEXT 5 ROWS ONLY"
      serviceOrderByID: "SELECT sro.site_ref as site_ref, sro.sro_num as sro_num,  sro.sro_type as sro_type, sro.start_date as start_date, sro.cust_po as cust_po, euser.enduser_code as enduser_code,  sro.ref_num as ref_num, sro.exch_rate as exch_rate, sro.uf_inititalcodate as uf_inititalcodate, curr.curr_code as curr_code, cust.cust_num as cust_num FROM dev_app.dbo.fs_sro_mst sro LEFT OUTER JOIN dev_app.dbo.customer_mst cust ON sro.cust_num = cust.cust_num AND cust.cust_seq = 0 left outer join dev_app.dbo.uec_enduser euser on sro.Uf_EndUserCode =euser.enduser_code LEFT OUTER JOIN dev_app.dbo.currparms_mst curr ON sro.site_ref = curr.site_ref WHERE sro.sro_stat = 'O' AND sro.sro_num = :Id"