#%RAML 1.0 DataType
type: object
properties:
  sro_line:
    type: string
  total_price:
    type: string
  total_cost_misc:
    type: string
  description:
    type: string
  line_type:
    type: string
  site_ref: 
    type: string
  sro_num:
    type: string
