#%RAML 1.0 NamedExample
customer:
    [{
        "cust_num": "C003785",
        "cust_seq": 0,
        "name": "Wesco Distribution - Kansas City, MO",
        "city": "Little Rock",
        "country": "United States",
        "site_ref": "USA"
    }]
