#%RAML 1.0 NamedExample
customer: [
    {
        "cust_num": "C001848",
        "cust_seq": 0,
        "name": "Wesco Distribution - 5837",
        "city": "Kansas City",
        "country": "United States",
        "site_ref": "USA"
    },
    {
        "cust_num": "C001849",
        "cust_seq": 0,
        "name": "Wesco Distribution Canada LP",
        "city": "Lithia Springs",
        "country": "United States",
        "site_ref": "USA"
    },
    {
        "cust_num": "C001852",
        "cust_seq": 0,
        "name": "Wesco Distribution  - Portland, ME",
        "city": "Portland",
        "country": "United States",
        "site_ref": "USA"
    }
]