#%RAML 1.0 NamedExample
{
  "customerOrder": [
    {
      "customerOrderNumber": "CO67890",
      "description": "800-amp busway",
      "partNumber": "BUS800-01",
      "shipDate": "2015-07-04T21:00:00",
      "quantity": 4,
      "plannedShipDate": "2015-07-04T21:00:00",
      "status": "SHIPPED",
      "statusChangeDate": "2015-07-04T21:00:00"
    },
    {
      "customerOrderNumber": "CO67890",
      "description": "800-amp busway",
      "partNumber": "BUS800-01",
      "shipDate": "2015-07-04T21:00:00",
      "quantity": 4,
      "plannedShipDate": "2015-07-04T21:00:00",
      "status": "SHIPPED",
      "statusChangeDate": "2015-07-04T21:00:00"
    }
  ]
}