#%RAML 1.0 NamedExample
EndUser: [
    {
        "enduser_code": "EU00000001",
        "legalentityname": "1st. Security Self Storage"
    },
    {
        "enduser_code": "EU00000002",
        "legalentityname": "325 Hudson"
    },
    {
        "enduser_code": "EU00000003",
        "legalentityname": "360 Power Solutions"
    },
    {
        "enduser_code": "EU00000004",
        "legalentityname": "4Degrees Colocation Inc."
    },
    {
        "enduser_code": "EU00000005",
        "legalentityname": "84 lumber"
    },
    {
        "enduser_code": "EU00000006",
        "legalentityname": "A & H Electric, Inc."
    }]