{
    "CustomerNo": "C005840",
    "OrderNo": "96465",
    "CustomerName": "Anexture",
    "ShipTo": "8",
    "EndUser": "EU0001517",
    "PO_Receive_Date": "12/6/2025",
    "On Site Date": "12/6/2025",
    "FOB": "Origin",
    "Line Discount(s)": " ",
    "Project_Code": "UNCC Science Bidg 415 V",
    "Override ID": " ",
    "Shipment": {
        "Terms": "N 30",
        "Ship_Via": "B WAY",
        "Ship_Method": " ",
        "Status": "Ordered",
        "Order_Date": "12/6/2025",
        "Cust_PO": "061-786291-1C2",
        "Order_Type": "Regular",
        "Ware_House": "MAIN",
        "UEC Regen Comm": {
            "Retention %": " ",
            "Retention Date": " "
        }
    },
    "Misc": {
        "External Order": "True",
        "CO Contract": " ",
        "EST_Total_Price": "173,392.00",
  "confirmation Reference": " "
    },
    "Site": {
        "Originating_Site": "USA",
        "Demanding Site": " ",
        "Demanding Site PO": " "
    }
}