#%RAML 1.0 NamedExample
serviceOrders: [
         {
           "sroNumber": "SRO12345",
           "customerPONumber": "PO98765",
           "customerOrderNumber": "CO67890",
           "projectCode": "PROJABC",
           "siteOrigination": "USA",
           "coInitialInvoiceDate": "2015-07-04T21:00:00",
           "coFinalInvoiceDate": "2015-07-04T21:00:00",
           "currency": "EUR",
           "exchangeRate": 1.17025,
           "lastModifiedDate": "2015-07-04T21:00:00",
           "sfWorkOrderId": "a00S000000abcdeIAA",
           "status": "WOCREATED"

         },
         { "sroNumber": "SRO12346",
           "customerPONumber": "PO98785",
           "customerOrderNumber": "CO67891",
           "projectCode": "PROJACC",
           "siteOrigination": "USA",
           "coInitialInvoiceDate": "2015-07-04T21:00:00",
           "coFinalInvoiceDate": "2015-07-04T21:00:00",
           "currency": "EUR",
           "exchangeRate": 1.17025,
           "lastModifiedDate": "2015-07-04T21:00:00",
           "sfWorkOrderId": "a00S000000abcdeIBA",
           "status": "WOCREATED"}
       ]

     