#%RAML 1.0 NamedExample
serviceOrders: [
          {"sro_num": "SRO12345",         
           "cust_po": "PO98765",   
           "sro_type": "SERVICES",      
           "start_date": "2015-06-04T21:00:00",
           "end_user_sfaccountid": "001S000000ghijklmNOP",
           "ref_num": "CO67890",
           "Uf_UEC_ProjectNumber": "PROJABC",
           "site_ref": "USA",
           "uf_inititalcodate": "2015-06-04T21:00:00",     
           "uf_finalcodate": "2015-06-30T21:00:00",
           "curr_code": "EUR",
           "exch_rate": 1.17025,    
           "lastModifiedDate": "2015-06-01T21:00:00",
           "customer_sfaccountid": "a00S000000abcdeIAA",
           "Uf_SFStatus": "INIT"}        
      ]
      