#%RAML 1.0 NamedExample
{
  "sro_num": "SO-1001",
  "sro_line": "1A",
  "site_ref": "SITE01",
  "total_price": "$2000.00",
  "total_cost_misc": "$3000.00",
  "description": "Startup service for busways",
  "line_type": ""

}