
  {
  "sro_num": "SO-1001",
  "sro_line": 1,
  "stat": "Closed",
  "UpdatedBy": "mulesoft_closure_batch",
  "total_billed": 20000,
  "qty_shipped": 1,
  "qty_returned": 0,
  "inspect_type": "Final",
  "description": "Completed installation and quality check",
  "use_est": false,
  "accum_wip": false,
  "awaiting_parts": false,
  "to_schedule": false,
  "extend_lbr_trans": true,
  "extend_matl_trans": true,
  "extend_misc_trans": false,
  "Uf_UEC_ProjectNumber": "UEC-PRJ-456"
}
