#%RAML 1.0 DataType
type: object
properties:
  customerOrderNumber: 
    type: string 
  description: 
    type: string
  partNumber: 
    type: string 
  shipDate: 
    type: datetime-only 
  quantity: 
    type: integer
  plannedShipDate: 
    type: datetime-only
  status:
    type: string
  statusChangeDate:
    type: datetime-only  