#%RAML 1.0 DataType
type: object
properties:
  sro_num:
    type: string
    required: true
  sro_line:
    type: integer
    required: true
  site_ref:
    type: string
    required: true
  product_code:
    type: string
    required: true
  description:
    type: string
    required: true
  qty:
    type: number
    required: true
  qty_conv:
    type: number
    required: true
  qty_issued:
    type: number
    required: true
  qty_issued_conv:
    type: number
    required: true
  qty_shipped:
    type: number
    required: true
  qty_shipped_conv:
    type: number
    required: true
  qty_returned:
    type: number
    required: true
  qty_returned_conv:
    type: number
    required: true
  qty_packed:
    type: number
    required: true
  u_m:
    type: string
    required: true
  pricecode:
    type: string
    required: true
  total_price:
    type: number
    required: true
  total_billed:
    type: number
    required: true
  total_cost_lbr:
    type: number
    required: true
  total_cost_matl:
    type: number
    required: true
  total_cost_misc:
    type: number
    required: true
  total_sales_tax1:
    type: number
    required: true
  total_sales_tax2:
    type: number
    required: true
  ser_num:
    type: string
    required: true
  stat:
    type: string
    required: true
  ref_type:
    type: string
    required: true
  ref_release:
    type: integer
    required: true
  ref_num:
    type: string
    required: true
  ref_line_suf:
    type: integer
    required: true
  dept:
    type: string
    required: true
  sro_type:
    type: string
    required: true
  contract:
    type: string
    required: true
  cont_line:
    type: integer
    required: true
  extend_lbr_trans:
    type: boolean
    required: true
  extend_matl_trans:
    type: boolean
    required: true
  extend_misc_trans:
    type: boolean
    required: true
  accum_wip:
    type: boolean
    required: true
  bill_code:
    type: string
    required: true
  bill_type:
    type: string
    required: true
  bill_stat:
    type: string
    required: true
  awaiting_parts:
    type: boolean
    required: true
  inspect_type:
    type: string
    required: true
  inc_num:
    type: string
    required: true
  cgs_rev_loc_labor:
    type: string
    required: true
  cgs_rev_loc_matl:
    type: string
    required: true
  cgs_rev_loc_misc:
    type: string
    required: true
  cust_item:
    type: string
    required: true
  use_est:
    type: boolean
    required: true
  to_schedule:
    type: boolean
    required: true
  partner_id:
    type: string
    required: true
  obal_line_matl:
    type: number
    required: true
  line_type:
    type: string
    required: true
  maint_seq:
    type: integer
    required: true
  exch_date:
    type: date-only
    required: true
  due_date:
    type: date-only
    required: true
  meter_amt:
    type: number
    required: true
  meter_date:
    type: string|nil
    required: false
  charfld1:
    type: string
    required: true
  charfld2:
    type: string
    required: true
  charfld3:
    type: string
    required: true
  decifld1:
    type: number
    required: true
  decifld2:
    type: number
    required: true
  decifld3:
    type: number
    required: true
  logifld:
    type: boolean
    required: true
  datefld:
    type: date-only
    required: true
  RowPointer:
    type: string
    required: true
  NoteExistsFlag:
    type: boolean
    required: true
  RecordDate:
    type: datetime
    required: true
  CreatedBy:
    type: string
    required: true
  UpdatedBy:
    type: string
    required: true
  CreateDate:
    type: datetime
    required: true
  InWorkflow:
    type: boolean
    required: true
  Uf_UEC_ProjectNumber:
    type: string
    required: true