#%RAML 1.0 DataType
type: object
properties:
      sro_num:
        type: string
        description: Unique Service Order Number from SyteLine.
        example: "SRO12345"
      cust_po:
        type: string
        description: Customer Purchase Order Number. 
        example: "PO98765"
      sro_type:
        type: string
        description: SRO work type. 
        example: "SERVICES"
      start_date:
        type: datetime-only
        description: Project start date. 
        example: "2015-06-04T21:00:00"
      end_user_sfaccountid:
        type: string
        description: End User Salesforce Account Id. 
        example: "2025-06-01"
      ref_num:
        type: string
        description: Associated Customer Order Number. 
        example: "CO67890"
      Uf_UEC_ProjectNumber:
        type: string
        description: Project Code related to the SRO. 
        example: "PROJABC"
      site_ref:
        type: string
        description: Originating site (USA, GBR, SGP). 
        enum: [ "USA", "GBR", "SGP" ]
        example: "USA"
      uf_inititalcodate:
        type: datetime-only
        description: Date of initial material shipment, from Syteline's "CO initial invoice" field. 
        example: "2015-06-04T21:00:00"
      uf_finalcodate:
        type: datetime-only
        description: Date of final material shipment, from Syteline's "CO final invoice" field. 
        example: "2015-06-04T21:00:00"
      curr_code:
        type: string
        description: Currency of the SRO (e.g., EUR, GBP, USD). 
        example: "EUR"
      exch_rate:
        type: number
        format: float
        description: Exchange rate for the SRO's currency (e.g., Euro to GBP or Euro to USD depending on site configuration). 
        example: 1.17025
      lastModifiedDate:
        type: datetime-only
        description: Last modified date of the SRO, for incremental fetching. 
        example: "2015-06-04T21:00:00"
      customer_sfaccountid:
        type: string
        description: Customer Salesforce Account Record ID.
        example: "a00S000000abcdeIAA"
      Uf_SFStatus:
        type: string
        description: Custom status field for SRO (e.g., NULL, INIT, FINAL) to manage processing. 
        example: "INIT"