#%RAML 1.0
title: Syteline ERP System API
protocols: [HTTPS,HTTP]

traits:
  errorResponse: !include traits/Errors.raml
  
types:
  customerDetails: !include dataTypes/customerListdataType.raml
  getCustomer: !include /dataTypes/getCustomerByIdResponseDataType.raml
  updateCustomerId: !include /dataTypes/updateCustomerIdRequestDataType.raml
  getCustomerId: !include /dataTypes/updateCustomerIdResponseDataType.raml
  EndUserList: !include /dataTypes/endUserListdataType.raml
  EndUserById: !include /dataTypes/getEndUserByIdResponseDataType.raml
  UpdateEndUserReq: !include /dataTypes/updateEndUserIdRequestDataType.raml
  UpdateEndUserRes: !include /dataTypes/updateEndUserIdResponseDataType.raml
  getServiceOrder: !include /dataTypes/getServiceOrdersResponseDataType.raml
  getServiceOrderId: !include /dataTypes/getServiceOrderIdResponseDataType.raml
  UpdateServiceOrderIdReq: !include /dataTypes/UpdateServiceOrderIdReqdataType.raml
  UpdateServiceOrderIdRes: !include /dataTypes/updateServiceOrderIdResponseDataType.raml
  getSOLineItems: !include /dataTypes/getServiceOrderLineItems.raml
  UpdtateSOLineitemReq: !include /dataTypes/updateSOLineItemsReq.raml
  UpdateSOLineItemRes: !include /dataTypes/updateSOLineItemsResponse.raml
  getServiceOrderLineItemById: !include /dataTypes/serviceOrderLineItemForSpecificId.raml
  customerOrderList: !include /dataTypes/customerOrdersList.raml
  getCustomerOrderId: !include /dataTypes/customerOrdersByIddataType.raml
/customer:
  /list:
    get:
      is: [errorResponse]
      description: "Get Customer by Id"
      displayName: "Get Customer Id" 
      responses:
        200:
          body:
            application/json:
              type: getCustomer
              example: !include examples/customerListResponse.raml    
  /{Id}:
    get:
      is: [errorResponse]
      description: "Get Customer by Id"
      displayName: "Get Customer Id" 
      responses:
        200:
          body:
            application/json:
              type: getCustomer
              example: !include examples/customerByIdRespone.raml
    put:
      is: [errorResponse]
      description: "Update Customer By Id"
      displayName: "CutomerById"
      body:
        application/json:
          type: updateCustomerId
          example: !include /examples/updateCustomerIdRequest.raml
            
      responses:
        200:
          body:
            application/json: 
              type: getCustomerId
              example: !include /examples/updateCustomerIdResponse.raml

              
/endusers:
  /list:
    get: 
      is: [errorResponse]
      description: "Get EndUsers By Id" 
      displayName: "EndUsers Id" 
      responses:
        200:
          body:
            application/json:
              type: EndUserList
              example: !include /examples/endUserListResponse.raml
  /{Id}:
    get: 
      is: [errorResponse]
      description: "Get EndUsers By Id" 
      displayName: "EndUsers Id" 
      responses:
        200:
          body:
            application/json:
              type: EndUserById
              example: !include /examples/endUserIdResponse.raml
                
    put:
      is: [errorResponse]
      description:  "Update endUsers By id"
      displayName: "EndUsers Id"
      body:
        application/json:
          type: UpdateEndUserReq
          example: !include /examples/updateEndUserIdRequest.raml
          
      responses:
        200:
          body:
            application/json:
              type: UpdateEndUserRes
              example: !include examples/updateEndUserIdResponse.raml
              
/serviceOrders:
  get: 
    is: [errorResponse]
    description: "Get ServiceOrders" 
    displayName: "ServiceOrders" 
    responses:
      200:
        body:
          application/json:
            type: getServiceOrder
            example: !include /examples/getServiceOrdersResponse.raml
              
  /{Id}:
    get: 
      is: [errorResponse]
      description: "Get ServiceOrders By Id" 
      displayName:  "ServiceOrders Id"
      responses:
        200:
          body:
            application/json:
              type: getServiceOrderId
              example: !include /examples/ServiceOrdersByIdResponse.raml
                  
    put:
      is: [errorResponse]
      description: "Update ServiceOrders By Id"
      displayName: "ServiceOrdersId"
      body:
        application/json:
          type: UpdateServiceOrderIdReq
          example: !include /examples/updateServiceOrderIdRequest.raml
          
      responses:
        200:
          body:
            application/json:
              type: UpdateServiceOrderIdRes
              example: !include /examples/updateServiceOrderIdResponse.raml                
/{serviceOrderId}/serviceOrderLineItems:
    get: 
        is: [errorResponse]
        description: "Get ServiceOrderLineItems By ServiceOrderIds" 
        responses:
          200:
            body:
              application/json:
                type: getSOLineItems
                example: !include /examples/getServiceOrderLineItems.raml
/serviceOrderLineItems/{Id}:
    put:
      is: [errorResponse]
      description:  "Update By Serviceorderlineitems"
      displayName: "ServiceOrderlineitems"
      body:
        application/json:
          type: UpdtateSOLineitemReq
          example: !include /examples/updateSOLineItemsRequest.raml
        
      responses:
        200:
          body:
            application/json:
              type: UpdateSOLineItemRes
              example: !include /examples/updateSOLineItemsResponse.raml
    get: 
      is: [errorResponse]
      description: "Get /serviceorderlineitems/{Id}" 
      displayName:  "serviceorderlineitems id"
      responses:
        200:
          body:
            application/json:
              type: getServiceOrderLineItemById
              example: !include /examples/serviceOrderLineItemForSpecificId.raml
             
/customerorders:
  /List:
    get: 
      is: [errorResponse]
      description: "Get CustomerOrders List" 
      displayName: "customerOrdersList" 
      responses:
        200:
          body:
            application/json:
              type: customerOrderList
              example: !include /examples/customerOrderList.raml

  /{Id}:
    get: 
      is: [errorResponse]
      description: "Get CustomerOrders By Id" 
      displayName: "CustomerOrder By Id" 
      responses:
        200:
          body:
            application/json:
              type: getCustomerOrderId
              example: !include /examples/customerOrdersByIdexample.raml
